
# The website we are testing
base.url=https://automationexercise.com

# Which browser to use: chrome, firefox, edge
browser=chrome


# Base URL for the REST API
api.base.url=https://automationexercise.com/api

# Where to save the Extent HTML report
extent.report.path=test-output/ExtentReport.html

# Where to save screenshots on failure
screenshot.path=test-output/screenshots/

#
 valid_email = parthadebnathm@gmail.com
 valid_password = 12345
 invalid_email= invalidemail@gmail.vom
 invalid_password= 2345

 
 
 #wait
 explicit.wait= 10
 implicit.wait= 10
 
 
 
screenshotPath=test-output/screenshots
takePassScreenshot=true
takeFailScreenshot=true
highlightElement=true